development:
  adapter: postgresql
  encoding: unicode
  database: fusionauth_dev
  pool: 2
  username: mcat56
  password: <%= ENV['LOCAL_PASSWORD'] %>
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
